local_configs:
  server:
    port: 8080
    host: "0.0.0.0"

  database:
    host: "localhost" #only in docker, change to localhost when needed
    port: "5432"
    name: "postgres"
    user: "postgres"
    schema: "public"
    password: "postgres"

  jwt:
    audience: "itv_users"
    domain: "https://vital-sync.uz"
    realm: "uz.vital-sync"
    secret: "TheB3s7Pa$$w0rdlnth3hlst0ryEv3R"
    access_token_ttl: 1800
    refresh_token_ttl: 604800