production_configs:
  server:
    port: 8080
    host: "localhost"

  database:
    host: "db"
    port: "6061"
    name: "vital-sync"
    user: "postgres"
    schema: "public"
    password: "vital-sync" # will be overwritten from os.Getenv()

  jwt:
    audience: "newUsersProd"
    domain: "https://google.com"
    realm: "com.google"
    secret: "SomeFuckingJwtCode" # will be overwritten from os.Getenv()
    access_token_ttl: 30
    refresh_token_ttl: 5040